org: dodo
org-billingmanager:
  ldap_users: []
  users: []
  ldap_group: ""
  ldap_groups: []
org-manager:
  ldap_users: []
  users:
  - admin
  - abby
  ldap_group: ""
  ldap_groups: []
org-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
  ldap_groups: []
enable-org-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 1000
total-services: -1
paid-service-plans-allowed: false
enable-remove-users: true
